[package]
name = "grs-wasm"
version = "0.1.0"
authors = ["Hillel Nagid"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "0.24.7"
ndarray = "0.15.6"
tch = "0.13.0"
wasm-bindgen = "0.2.87"
